# MODEL
levels: 2
tmp_abs_factor: 6
dec_stddev: 1.0
enc_dense_embed_size: 1000
cell_type: RSSMCell
cell_stoch_size: 20
cell_deter_size: 200
cell_embed_size: 200

# DATASET
datadir: null
dataset: bouncing_balls
seq_len: 35
eval_seq_len: 35
channels: 3

# TRAINING
lr: 0.0003
batch_size: 32
num_epochs: 300

# SUMMARIES
logdir: null
open_loop_ctx: 12
num_val_batches: 1
save_named_model_every: 5000
